[clickhouse]
url = "http://localhost:8123"
database = "mining"
username = "default"
password = "5555"
batch_size = 1000
batch_flush_interval_secs = 5
pool_size = 5
base_retry_delay_ms = 100
max_retry_delay_secs = 1

[processing]
primary_channel_buffer_size = 10000
backup_check_interval_secs = 1
block_verification_max_retries = 5
block_verification_retry_delay_ms = 1000

[bitcoin_rpc]
url = ""
port = 0
user = ""
password = ""
