x-def-logging: &default-logging
  logging:
    driver: "loki"
    options:
      loki-url: "http://84.201.144.127:3100/loki/api/v1/push"
      loki-batch-size: "100"
      loki-retries: 2
      loki-max-backoff: 1000ms
      loki-timeout: 1s

services:
    pool:
        image: ${NEXUS_URL}/rrp-pool:latest
        restart: always
        <<: *default-logging
        volumes:
          - /var/log/pool:/app/logs
        environment:
          - SHARES_LOGGER__CLICKHOUSE__BATCH_SIZE=1000
          - SHARES_LOGGER__PROCESSING__PRIMARY_CHANNEL_BUFFER_SIZE=10000
          - SHARES_LOGGER__CLICKHOUSE__URL=${CLICKHOUSE_URL}
          - SHARES_LOGGER__CLICKHOUSE__USERNAME=${CLICKHOUSE_USER}
          - SHARES_LOGGER__CLICKHOUSE__PASSWORD=${CLICKHOUSE_PASSWORD}
          - POOL__COINBASE_OUTPUTS_0_OUTPUT_SCRIPT_TYPE=${COINBASE_TYPE}
          - POOL__COINBASE_OUTPUTS_0_OUTPUT_SCRIPT_VALUE=${COINBASE_VALUE}
          - POOL__TEST_ONLY_LISTEN_ADDRESS_PLAIN=${POOL_PLAIN_PORT}
          - POOL__LISTEN_ADDRESS=0.0.0.0:${POOL_PORT}
          - POOL__TP_ADDRESS=${NODE_HOST}:${NODE_PORT}
          - POOL__TP_AUTHORITY_PUBLIC_KEY=${NODE_KEY}
          - TPROXY_LOG_LEVEL_FILE=ERROR
          - TPROXY_LOG_LEVEL_CONSOLE=ERROR
        container_name: pool
        network_mode: host
 
    translator:
        image: ${NEXUS_URL}/rrp-translator:latest
        restart: always
        <<: *default-logging
        volumes:
          - /var/log/translator:/app/logs
        environment:
          - REDROCK_API_URL=${REDROCK_API_URL}
          - REDROCK_API_KEY=${REDROCK_API_KEY}
          - REDROCK_TIMEOUT_SECONDS=5
          - SHARES_LOGGER__CLICKHOUSE__BATCH_FLUSH_INTERVAL_SECS=60
          - SHARES_LOGGER__CLICKHOUSE__BATCH_SIZE=1000
          - SHARES_LOGGER__PROCESSING__PRIMARY_CHANNEL_BUFFER_SIZE=10000
          - SHARES_LOGGER__CLICKHOUSE__URL=${CLICKHOUSE_URL}
          - SHARES_LOGGER__CLICKHOUSE__USERNAME=${CLICKHOUSE_USER}
          - SHARES_LOGGER__CLICKHOUSE__PASSWORD=${CLICKHOUSE_PASSWORD}
          - TPROXY_LOG_LEVEL_FILE=DEBUG
          - TPROXY_LOG_LEVEL_CONSOLE=DEBUG
          - TPROXY_METRICS_PORT=${METRICS_PORT}
          - TPROXY_UPSTREAM_PORT=${POOL_PORT}
          - TPROXY_DOWNSTREAM_PORT=${TRANSLATOR_PORT}
        container_name: translator
        network_mode: host
