services:
    clickhouse:
        image: clickhouse:latest
        container_name: clickhouse
        environment:
          - CLICKHOUSE_DB=mining
          - CLICKHOUSE_USER=${CLICKHOUSE_USER}
          - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
        restart: always
        ports:
          - 8123:8123
        network_mode: host
    
    pool:
        image: ${NEXUS_URL}/rrp-pool:latest
        restart: always
        container_name: pool
        network_mode: host
 
    translator:
        image: ${NEXUS_URL}/rrp-translator:latest
        restart: always
        container_name: translator
        network_mode: host
