[package]
name = "shares-logger"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.10"
hex = "0.4"
tokio = { version = "1.0", features = ["rt", "sync", "rt-multi-thread"] }
once_cell = "1.8"